# Generated by Django 4.0.3 on 2022-05-04 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employees_avatar_employees_cv_alter_employees_age'),
        ('employees', '0003_alter_employees_age'),
    ]

    operations = [
    ]
